[package]
name = "riew"
version = "0.1.0"
authors = ["BenoÃ®t Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
clap = "3"
once_cell = "1"
owning_ref = "0.4"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["image", "ttf"]

