[package]
name = "riew"
version = "1.1.0"
authors = ["BenoÃ®t Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
once_cell = "1"
owning_ref = "0.4"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image", "ttf"]

